apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: flask-pod
  name: flask-pod
  namespace: flask
spec:
  containers:
  - image: 638733641367.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment2-flask:v1.0
    name: flask-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}