apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: mysql
  name: sql-pod
  namespace: sql
spec:
  imagePullSecrets:
  - name: ecr-secret
  containers:
  - image: ECRURI/clo835-assignment2-sql:v1.0
    name: sql-pod
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: "pw"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}