apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sql-pod
  name: sql-pod
  namespace: sql
spec:
  imagePullSecrets:
  - name: ecr-secret
  containers:
  - image: 638733641367.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment2-sql:v1.0
    name: sql-pod
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: "pw"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}