apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: sql
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: sql-pod
          image: "$(ECR_REGISTRY)/clo835-assignment2-sql:v1.0"
          env:
            - name: ECR_REGISTRY
              valueFrom:
                configMapKeyRef:
                  name: ecr-config
                  key: ECR_REGISTRY
            - name: MYSQL_ROOT_PASSWORD
              value: "pw"
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
