apiVersion: v1
kind: Service
metadata:
  name: sql-service
  namespace: sql
spec:
  selector:
    run: sql-pod
  ports:
    - protocol: TCP
      port: 3306    # ClusterIP port
      targetPort: 3306 # Container port
  type: ClusterIP  # Internal service only