apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sql-pod
  name: sql-pod
spec:
  containers:
  - image: 638733641367.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment2-sql:v1.0
    name: sql-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}